services:
  - type: web
    name: remove-bg-api
    env: python
    runtime: python-3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
